describe('PIM', () => {
    it('1 - Clico na aba PIM', () => {
    cy.visit(Cypress.env('login_URL'))
    cy.get('[name="username"]').type(Cypress.env('usuario'))
    cy.get('[name="password"]').type(Cypress.env('senha'))
    cy.get('.oxd-button').click()
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').contains('Dashboard')
    cy.get(':nth-child(2) > .oxd-main-menu-item').click()
    cy.get('.oxd-topbar-header-title').contains('PIM')
  })
    it('2 - Seleciono o status empresarial', () => {
    cy.visit(Cypress.env('login_URL'))
    cy.get('[name="username"]').type(Cypress.env('usuario'))
    cy.get('[name="password"]').type(Cypress.env('senha'))
    cy.get('.oxd-button').click()
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').contains('Dashboard')
    cy.get(':nth-child(2) > .oxd-main-menu-item').click()
    cy.get('.oxd-topbar-header-title').contains('PIM')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text').click()
    cy.contains('Full-Time Contract').click();
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.contains('.orangehrm-horizontal-padding > .oxd-text', 'No Records Found').should('not.exist')
  })
    it('3 - Seleciono o título do trabalho', () => {
    cy.visit(Cypress.env('login_URL'))
    cy.get('[name="username"]').type(Cypress.env('usuario'))
    cy.get('[name="password"]').type(Cypress.env('senha'))
    cy.get('.oxd-button').click()
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').contains('Dashboard')
    cy.get(':nth-child(2) > .oxd-main-menu-item').click()
    cy.get('.oxd-topbar-header-title').contains('PIM')
    cy.get(':nth-child(6) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text').click()
    cy.contains('Chief Financial').click();
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.contains('.orangehrm-horizontal-padding > .oxd-text', 'No Records Found').should('not.exist')
  })
    it('4 - Insiro valores de apuração não existentes', () => {
    cy.visit(Cypress.env('login_URL'))
    cy.get('[name="username"]').type(Cypress.env('usuario'))
    cy.get('[name="password"]').type(Cypress.env('senha'))
    cy.get('.oxd-button').click()
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').contains('Dashboard')
    cy.get(':nth-child(2) > .oxd-main-menu-item').click()
    cy.get('.oxd-topbar-header-title').contains('PIM')
    cy.get(':nth-child(6) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text').click()
    cy.contains('Account Assistant').click();
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.get('.orangehrm-horizontal-padding > .oxd-text').contains('No Records Found')
  })
})